os: linux

services:
- docker

archlinux:
  mount:
  - ~/.pkg-cache:/var/cache/pacman/pkg
  before_install:
  - "sudo ln -s /dev/null /etc/pacman.d/hooks/package-cleanup.hook"
  script:
  - "makepkg"

script:
- "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
